"""Generate docs/reference.md from the server's tools, prompts and CLI.

The tool docstrings, signatures and result models are what MCP clients
see, so they are the source of truth for the reference; this script
renders them, and a test fails when the committed file no longer matches.
Run it after changing a tool::

    uv run scripts/generate_reference.py

Sections follow the tool modules in the order the server registers them,
with each module's docstring as the section introduction. Result models
that several tools share are described once, in the last section.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
import textwrap
from pathlib import Path
from typing import TYPE_CHECKING, Any

from mcp.server.mcpserver import MCPServer

from mcp_score.cli import build_parser
from mcp_score.server import TOOL_MODULES

if TYPE_CHECKING:
    from collections.abc import Iterable

    from mcp.types import Prompt, Tool

    from mcp_score.tools import ToolModule

REFERENCE_PATH = Path(__file__).resolve().parent.parent / "docs" / "reference.md"

PREAMBLE = "\n".join(
    [
        "<!-- Generated by scripts/generate_reference.py from the tool docstrings."
        " Do not edit by hand. -->",
        "",
        "# Tool reference",
        "",
        "> Reference -- every MCP tool and prompt the server provides, and the CLI.",
        "",
        "Every tool publishes the schema of its result, described under the tool"
        " and, for the result types tools share, in the last section. A tool that"
        " cannot do what was asked fails with an MCP tool error whose message says"
        " why."
        " Connection, analysis and manipulation tools need a connected"
        " application (MuseScore, or experimentally Dorico or Sibelius);"
        " generation and"
        " rendering tools work on files.",
    ]
)

ARGS_HEADING = "Args:"
RESULT_TYPES_TITLE = "## Result types"
SCHEMA_TYPE_NAMES: dict[str, str] = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "array": "list",
    "object": "dict",
    "null": "None",
}
REQUIRED = "(required)"
HELP_COLUMNS = "80"


# ── Docstrings ────────────────────────────────────────────────────────


def split_docstring(text: str) -> tuple[str, dict[str, str], str]:
    """Split a Google-style docstring into body, argument descriptions, tail."""
    lines = text.strip().splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if line.strip() == ARGS_HEADING)
    except StopIteration:
        return "\n".join(lines).strip(), {}, ""
    arguments: dict[str, str] = {}
    current: str | None = None
    end = len(lines)
    for index in range(start + 1, len(lines)):
        line = lines[index]
        if not line.strip():
            end = index
            break
        stripped = line.strip()
        indent = len(line) - len(line.lstrip())
        if indent <= 4 and ":" in stripped:
            current, _, description = stripped.partition(":")
            arguments[current.strip()] = description.strip()
        elif current is not None:
            arguments[current] = f"{arguments[current]} {stripped}"
    body = "\n".join(lines[:start]).strip()
    return body, arguments, textwrap.dedent("\n".join(lines[end:])).strip()


# ── Schema ────────────────────────────────────────────────────────────


def schema_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "anyOf" in schema:
        options: list[dict[str, Any]] = schema["anyOf"]
        return " | ".join(schema_type(option) for option in options)
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if schema.get("type") == "array":
        items: dict[str, Any] = schema.get("items", {})
        return f"list[{schema_type(items)}]"
    return SCHEMA_TYPE_NAMES.get(str(schema.get("type")), str(schema.get("type")))


def default_text(name: str, schema: dict[str, Any], required: set[str]) -> str:
    if name in required:
        return REQUIRED
    value = schema.get("default")
    return "None" if value is None else json.dumps(value)


# ── Markdown ──────────────────────────────────────────────────────────


def code(text: str) -> str:
    return f"`{text}`"


def table(headers: list[str], rows: list[list[str]]) -> str:
    """A pipe table padded the way prettier formats it."""
    cells = [[cell.replace("|", "\\|") for cell in row] for row in [headers, *rows]]
    widths = [max(len(row[i]) for row in cells) for i in range(len(headers))]
    lines = [
        "| " + " | ".join(cell.ljust(widths[i]) for i, cell in enumerate(row)) + " |"
        for row in cells
    ]
    separator = "| " + " | ".join("-" * width for width in widths) + " |"
    return "\n".join([lines[0], separator, *lines[1:]])


def parameter_table(schema: dict[str, Any], descriptions: dict[str, str]) -> str:
    properties: dict[str, dict[str, Any]] = schema.get("properties", {})
    if not properties:
        return "No parameters."
    required = set(schema.get("required", []))
    rows = [
        [
            code(name),
            code(schema_type(property_schema)),
            code(default_text(name, property_schema, required))
            if name not in required
            else REQUIRED,
            descriptions.get(name, ""),
        ]
        for name, property_schema in properties.items()
    ]
    return table(["Parameter", "Type", "Default", "Description"], rows)


def field_table(schema: dict[str, Any]) -> str:
    """The fields of a result model, as the schema describes them."""
    properties: dict[str, dict[str, Any]] = schema.get("properties", {})
    if not properties and schema.get("additionalProperties"):
        return "Whatever fields the application sends."
    rows = [
        [code(name), code(schema_type(field)), field.get("description", "")]
        for name, field in properties.items()
    ]
    return table(["Field", "Type", "Description"], rows)


def is_wrapped(schema: dict[str, Any]) -> bool:
    """Whether the server wrapped a plain return value as ``{"result": ...}``."""
    return str(schema.get("title", "")).endswith("Output") and list(
        schema.get("properties", {})
    ) == ["result"]


def render_result(schema: dict[str, Any], shared: dict[str, dict[str, Any]]) -> str:
    """Describe a tool's result; nested models go to *shared* for the last section."""
    definitions: dict[str, dict[str, Any]] = schema.get("$defs", {})
    shared.update(definitions)
    if is_wrapped(schema):
        return f"**Returns** {code(schema_type(schema['properties']['result']))}."
    description = str(schema.get("description", "")).strip()
    heading = f"**Returns** {code(str(schema['title']))}"
    intro = f"{heading}: {description}" if description else f"{heading}."
    return f"{intro}\n\n{field_table(schema)}"


def render_tool(tool: Tool, shared: dict[str, dict[str, Any]]) -> str:
    body, arguments, tail = split_docstring(tool.description or "")
    parts = [
        f"### {code(tool.name)}",
        body,
        parameter_table(tool.input_schema, arguments),
        tail,
    ]
    if tool.output_schema is not None:
        parts.append(render_result(tool.output_schema, shared))
    return "\n\n".join(part for part in parts if part)


def render_result_type(name: str, schema: dict[str, Any]) -> str:
    description = str(schema.get("description", "")).strip()
    parts = [f"### {code(name)}", description, field_table(schema)]
    return "\n\n".join(part for part in parts if part)


def render_result_types(shared: dict[str, dict[str, Any]]) -> str:
    entries = [render_result_type(name, shared[name]) for name in sorted(shared)]
    return "\n\n".join([RESULT_TYPES_TITLE, *entries])


def render_prompt(prompt: Prompt) -> str:
    description = (prompt.description or "").strip()
    return f"### Prompt {code(prompt.name)}\n\n{description}"


def section_title(module: ToolModule) -> str:
    name = str(getattr(module, "__name__", "tools")).rsplit(".", 1)[-1]
    return f"## {name.capitalize()} tools"


def section_intro(module: ToolModule) -> str:
    docstring = getattr(module, "__doc__", None) or ""
    return docstring.strip()


async def render_section(module: ToolModule, shared: dict[str, dict[str, Any]]) -> str:
    server = MCPServer("reference")
    module.register(server)
    tools = await server.list_tools()
    prompts = await server.list_prompts()
    entries: Iterable[str] = (
        [section_title(module), section_intro(module)]
        + [render_tool(tool, shared) for tool in tools]
        + [render_prompt(prompt) for prompt in prompts]
    )
    return "\n\n".join(entry for entry in entries if entry)


def render_cli() -> str:
    os.environ["COLUMNS"] = HELP_COLUMNS
    help_text = build_parser().format_help().rstrip()
    return f"## CLI\n\n```\n{help_text}\n```"


async def render_reference() -> str:
    shared: dict[str, dict[str, Any]] = {}
    sections = [await render_section(module, shared) for module in TOOL_MODULES]
    parts = [PREAMBLE.rstrip(), *sections, render_result_types(shared), render_cli()]
    return "\n\n".join(parts) + "\n"


# ── Entry point ───────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").split("\n", 1)[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if docs/reference.md differs instead of writing it",
    )
    args = parser.parse_args(argv)
    generated = asyncio.run(render_reference())
    if args.check:
        if REFERENCE_PATH.read_text() != generated:
            sys.stderr.write(f"{REFERENCE_PATH} is out of date; run this script.\n")
            return 1
        return 0
    REFERENCE_PATH.write_text(generated)
    return 0


if __name__ == "__main__":
    sys.exit(main())
